promql_list:
  - promql: count by (namespace) (kube_configmap_info{namespace !~ "kube-system|kube-public"})
    query_range: 1h
    query_step: 15s
  - promql: sum by (namespace, node) (kube_pod_container_resource_requests_memory_bytes{namespace !~ "kube-system|kube-public"})
    query_range: 1h
    query_step: 15s
  - promql: sum(kube_node_status_allocatable_memory_bytes{node!~"virtual-kubelet.*"})
    query_range: 1h
    query_step: 15s
  - promql: sum(kube_pod_container_resource_requests_memory_bytes{}) / sum(kube_node_status_allocatable_memory_bytes{node!~"virtual-kubelet.*"})
    query_range: 1h
    query_step: 15s
  - promql: sum(kube_pod_container_resource_limits_memory_bytes{}) / sum(kube_node_status_allocatable_memory_bytes{node!~"virtual-kubelet.*"})
    query_range: 1h
    query_step: 15s
  - promql: sum(kube_node_status_allocatable_cpu_cores{node!~"virtual-kubelet.*"})
    query_range: 1h
    query_step: 15s
  - promql: sum(kube_pod_container_resource_requests_cpu_cores{}) / sum(kube_node_status_allocatable_cpu_cores{node!~"virtual-kubelet.*"})
    query_range: 1h
    query_step: 15s
  - promql: sum(kube_pod_container_resource_limits_cpu_cores{}) / sum(kube_node_status_allocatable_cpu_cores{node!~"virtual-kubelet.*"})
    query_range: 1h
    query_step: 15s
  - promql:  count by (namespace) (kube_node_info{node!~"virtual-kubelet.*"})
    query_range: 1h
    query_step: 15s
  - promql:  count by (namespace) (kube_node_info{node!~"virtual-kubelet.*", created_by_kind!~"<none>|Job"})
    query_range: 1h
    query_step: 15s
  - promql: sum(kube_node_status_allocatable{resource="pods", unit="integer",node!~"virtual-kubelet.*"})
    query_range: 1h
    query_step: 15s
  - promql: count(kube_service_info{namespace !~ "kube-system|kube-public"}) by(namespace)
    query_range: 1h
    query_step: 15s
  - promql: count (count(kube_pod_container_info{namespace !~ "kube-system|kube-public"}) by(container,namespace)) by (namespace)
    query_range: 6h
    query_step: 30s
  - promql: sum (kube_pod_container_resource_requests{resource="cpu", unit="core", node!~"virtual-kubelet.*"}) by (node)
    query_range: 6h
    query_step: 30s
  - promql: sum(kube_pod_container_resource_limits{resource="cpu", unit="core", node!~"virtual-kubelet.*"}) by (node)
    query_range: 6h
    query_step: 30s
  - promql: sum(kube_pod_container_resource_requests{resource="cpu", unit="core",node!~"virtual-kubelet.*", namespace !~ "kube-system|kube-public"}) by (container,pod,node,namespace)
    query_range: 6h
    query_step: 30s
  - promql: sum(kube_pod_container_resource_requests{resource="memory", unit="byte",node!~"virtual-kubelet.*", namespace !~ "kube-system|kube-public"}) by (container,pod,node,namespace)
    query_range: 6h
    query_step: 30s
  - promql: count by (namespace) (kube_cronjob_info{}) - count by (namespace) (kube_job_status_failed{})
    query_range: 6h
    query_step: 30s
  - promql: count by (namespace) (kube_cronjob_next_schedule_time{} -  time() < 3600)
    query_range: 6h
    query_step: 30s
  - promql: sum by (storageclass) (kube_persistentvolume_info{})
    query_range: 6h
    query_step: 30s
  - promql: sum by (namespace, storageclass) (kube_persistentvolumeclaim_info{})
    query_range: 48h
    query_step: 60s
  - promql: count (kube_pod_container_info{}) - count (kube_pod_container_info{})
    query_range: 48h
    query_step: 60s
  - promql: sum by (namespace) (rate(kube_pod_status_ready{}[1m]))
    query_range: 48h
    query_step: 60s
  - promql: sum by (namespace, node) (kube_pod_container_resource_limits_memory_bytes{}) /1024/1024 - sum by (namespace, node) (kube_pod_container_resource_limits_memory_bytes{}) /1024/1024
    query_range: 48h
    query_step: 60s
  - promql: sum by (node) (kube_node_status_allocatable_memory_bytes{}) - sum by (node) (kube_pod_container_resource_requests_memory_bytes{})
    query_range: 48h
    query_step: 60s
  - promql: sum by (namespace, node) (kube_pod_container_resource_requests_cpu_cores{}) - sum by (namespace, node) (kube_pod_container_resource_limits_cpu_cores{})
    query_range: 48h
    query_step: 60s
  - promql: count by (namespace) (kube_cronjob_info{}) - count by (namespace) (kube_job_status_failed{})
    query_range: 48h
    query_step: 60s
  - promql: topk(20, sum by (pod) (kube_pod_container_info{}))
    query_range: 48h
    query_step: 60s
  - promql: topk(20, kube_pod_container_resource_requests_memory_bytes{})
    query_range: 48h
    query_step: 60s
  - promql: rate(scrape_series_added{}[1m])
    query_range: 48h
    query_step: 60s
  - promql: rate(kube_daemonset_status_number_ready{}[1m])
    query_range: 48h
    query_step: 60s
  - promql: sum by (namespace) (rate(kube_job_status_failed{}[1m]))
    query_range: 48h
    query_step: 60s